//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class agencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agencias()
        {
            this.ahorrosContractual = new HashSet<ahorrosContractual>();
            this.ahorrospermanentes = new HashSet<ahorrospermanentes>();
            this.aportessociales = new HashSet<aportessociales>();
            this.costosliquidacion = new HashSet<costosliquidacion>();
            this.empresas = new HashSet<empresas>();
            this.hasociados = new HashSet<hasociados>();
            this.hnits = new HashSet<hnits>();
            this.sahorrosContractual = new HashSet<sahorrosContractual>();
            this.sahorrospermanentes = new HashSet<sahorrospermanentes>();
            this.ahorrosAtermino = new HashSet<ahorrosAtermino>();
            this.novedadesvariasnocausadas = new HashSet<novedadesvariasnocausadas>();
            this.sahorrosAtermino = new HashSet<sahorrosAtermino>();
            this.seguimientocredito = new HashSet<seguimientocredito>();
            this.seguimientocredito1 = new HashSet<seguimientocredito>();
            this.sahorrosalavista = new HashSet<sahorrosalavista>();
            this.dependenciasempresas = new HashSet<dependenciasempresas>();
        }
    
        public int codigoagencia { get; set; }
        public string nombreagencia { get; set; }
        public string codpais { get; set; }
        public string codciudad { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string coddepto { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<System.DateTime> fechasistema { get; set; }
        public string email { get; set; }
        public string correosaliente { get; set; }
        public System.DateTime fechatrabajo { get; set; }
        public string rutaopa { get; set; }
        public string clavecorreo { get; set; }
        public string tipocorreo { get; set; }
        public short idagencias { get; set; }
        public string codigoagenciaseguro { get; set; }
        public string protocolodeenvio { get; set; }
        public string nombreperfil { get; set; }
        public Nullable<bool> web { get; set; }
        public Nullable<byte> szin { get; set; }
        public Nullable<bool> zsisco { get; set; }
    
        public virtual ciudades ciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ahorrosContractual> ahorrosContractual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ahorrospermanentes> ahorrospermanentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aportessociales> aportessociales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<costosliquidacion> costosliquidacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empresas> empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hasociados> hasociados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hnits> hnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sahorrosContractual> sahorrosContractual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sahorrospermanentes> sahorrospermanentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ahorrosAtermino> ahorrosAtermino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<novedadesvariasnocausadas> novedadesvariasnocausadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sahorrosAtermino> sahorrosAtermino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seguimientocredito> seguimientocredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seguimientocredito> seguimientocredito1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sahorrosalavista> sahorrosalavista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dependenciasempresas> dependenciasempresas { get; set; }
    }
}
