//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class asociados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asociados()
        {
            this.ahorrosContractual = new HashSet<ahorrosContractual>();
            this.ahorrospermanentes = new HashSet<ahorrospermanentes>();
            this.aportessociales = new HashSet<aportessociales>();
            this.personacargo = new HashSet<personacargo>();
            this.ahorrosalavista = new HashSet<ahorrosalavista>();
            this.ahorrosAtermino = new HashSet<ahorrosAtermino>();
            this.novedadesvariasnocausadas = new HashSet<novedadesvariasnocausadas>();
        }
    
        public long cedulasociado { get; set; }
        public string codnit { get; set; }
        public string codempresa { get; set; }
        public string coddependencia { get; set; }
        public string periododeduce { get; set; }
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public string deduceocacional { get; set; }
        public string sexo { get; set; }
        public string estudios { get; set; }
        public string codprofesion { get; set; }
        public string estadocivil { get; set; }
        public string nroacta { get; set; }
        public Nullable<System.DateTime> fechaacta { get; set; }
        public decimal salario { get; set; }
        public string codempresalabora { get; set; }
        public Nullable<System.DateTime> fechaingresoLabora { get; set; }
        public string tipocontrato { get; set; }
        public Nullable<System.DateTime> fechaterminacontrato { get; set; }
        public string cargo { get; set; }
        public string codbanco { get; set; }
        public string numerocuenta { get; set; }
        public int agencia { get; set; }
        public long codanalista { get; set; }
        public string rutaanalista { get; set; }
        public string tipocuenta { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> ultimaactualizacion { get; set; }
        public string operadoractualizo { get; set; }
        public string paisnace { get; set; }
        public string dptonace { get; set; }
        public string ciudadnace { get; set; }
        public long idnits { get; set; }
        public Nullable<short> idtipovivienda { get; set; }
        public Nullable<byte> szin { get; set; }
        public Nullable<short> idtiposalario { get; set; }
        public string tipopacto { get; set; }
        public Nullable<byte> web { get; set; }
        public decimal idasociados { get; set; }
        //public string codigotipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ahorrosContractual> ahorrosContractual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ahorrospermanentes> ahorrospermanentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aportessociales> aportessociales { get; set; }
        public virtual ciudades ciudades { get; set; }
        public virtual departamentos departamentos { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual nits nits { get; set; }
        public virtual pais pais { get; set; }
        public virtual profesiones profesiones { get; set; }
        public virtual profesiones profesiones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personacargo> personacargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ahorrosalavista> ahorrosalavista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ahorrosAtermino> ahorrosAtermino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<novedadesvariasnocausadas> novedadesvariasnocausadas { get; set; }
        public virtual dependenciasempresas dependenciasempresas { get; set; }
    }
}
