//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class costosliquidacion
    {
        public int registro { get; set; }
        public Nullable<decimal> nrosolicitud { get; set; }
        public Nullable<decimal> pagare { get; set; }
        public string codcuenta { get; set; }
        public Nullable<decimal> valorcosto { get; set; }
        public string tipocosto { get; set; }
        public Nullable<decimal> valorcancelado { get; set; }
        public Nullable<int> nroliquidacion { get; set; }
        public Nullable<System.DateTime> fechacancelado { get; set; }
        public Nullable<System.DateTime> fechapago { get; set; }
        public int agencia { get; set; }
        public string periododegracia { get; set; }
        public Nullable<decimal> numerocosto { get; set; }
        public Nullable<bool> web { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
    
        public virtual agencias agencias { get; set; }
        public virtual creditos creditos { get; set; }
        public virtual plancuentas plancuentas { get; set; }
    }
}
