//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentasnovedadesvarias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuentasnovedadesvarias()
        {
            this.novedadesvariasnocausadas = new HashSet<novedadesvariasnocausadas>();
        }
    
        public string codnovedad { get; set; }
        public string codcuenta { get; set; }
        public string tiponovedad { get; set; }
        public string controlenlaentidad { get; set; }
        public string naturalezamovimientosrecaudos { get; set; }
        public short idcuentasnovedadesvarias { get; set; }
        public Nullable<bool> zsisco { get; set; }
    
        public virtual plancuentas plancuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<novedadesvariasnocausadas> novedadesvariasnocausadas { get; set; }
    }
}
