//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class destinos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public destinos()
        {
            this.tasasporplazos = new HashSet<tasasporplazos>();
        }
    
        public string Coddestino { get; set; }
        public string nombredestino { get; set; }
        public string codlinea { get; set; }
        public string Estado { get; set; }
        public string clase { get; set; }
        public Nullable<decimal> tasacolocacionminima { get; set; }
        public Nullable<decimal> tasacolocacionmaxima { get; set; }
        public Nullable<decimal> tasapordefecto { get; set; }
        public Nullable<decimal> tasaMora { get; set; }
        public Nullable<decimal> tasacolocaciondtf { get; set; }
        public double montominimo { get; set; }
        public double montomaximo { get; set; }
        public int peridominimodias { get; set; }
        public int periodomaximodias { get; set; }
        public string pidenroliquidacion { get; set; }
        public string pidenropagareliquidacion { get; set; }
        public string pidefechainicialcredito { get; set; }
        public string financiainterescorriente { get; set; }
        public string capitalizainteres { get; set; }
        public string cobrainteresabonoextradias { get; set; }
        public string causainteresanticipado { get; set; }
        public string igualPlanPago { get; set; }
        public int periodogracia { get; set; }
        public string formacobrodtf { get; set; }
        public string utilizarangostasaoplazo { get; set; }
        public string manejacalendariofestivo { get; set; }
        public string acumulafestivos { get; set; }
        public string tipotasavariable { get; set; }
        public string conservapuntostasavariable { get; set; }
        public short iddestino { get; set; }
        public string extrasreestructuran { get; set; }
        public string periodicidad { get; set; }
        public Nullable<bool> web { get; set; }
        public Nullable<byte> szin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tasasporplazos> tasasporplazos { get; set; }
        public virtual lineas lineas { get; set; }
    }
}
