//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class divisionciiu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public divisionciiu()
        {
            this.nits = new HashSet<nits>();
        }
    
        public string codciiu { get; set; }
        public string coddivision { get; set; }
        public string nombre { get; set; }
        public decimal iddivisionciiu { get; set; }
        public Nullable<byte> szin { get; set; }
        public short web { get; set; }
    
        public virtual ciiu ciiu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nits> nits { get; set; }
    }
}
