//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresas()
        {
            this.asociados = new HashSet<asociados>();
        }
    
        public string codempresa { get; set; }
        public long nitempresa { get; set; }
        public string nombreempresa { get; set; }
        public string codciiu { get; set; }
        public string direccion { get; set; }
        public string codpais { get; set; }
        public string ciudad { get; set; }
        public string departamento { get; set; }
        public string telefono { get; set; }
        public string representante { get; set; }
        public string pagador { get; set; }
        public string formapago { get; set; }
        public Nullable<int> numerosemanas { get; set; }
        public Nullable<int> numerodecadas { get; set; }
        public Nullable<int> numerocatorcenas { get; set; }
        public Nullable<int> numeroquincenas { get; set; }
        public Nullable<int> numeromes { get; set; }
        public Nullable<System.DateTime> fechaingreso { get; set; }
        public Nullable<System.DateTime> fecharetiro { get; set; }
        public string empresaretirados { get; set; }
        public string cobramora { get; set; }
        public Nullable<System.DateTime> fechacorte { get; set; }
        public string diasgraciasemana { get; set; }
        public string diasgraciaquincena { get; set; }
        public string diasgraciadecada { get; set; }
        public string diasgraciacatorcenas { get; set; }
        public string diasgraciasmes { get; set; }
        public string capturadatos { get; set; }
        public string periododeduccion { get; set; }
        public string email { get; set; }
        public int agencia { get; set; }
        public string morapornomina { get; set; }
        public string certificada { get; set; }
        public short idempresas { get; set; }
        public Nullable<short> numerobimes { get; set; }
        public Nullable<short> numerotrimes { get; set; }
        public Nullable<short> numerosemestre { get; set; }
        public Nullable<bool> web { get; set; }
        public string regional { get; set; }
        public Nullable<short> numeroventiochenas { get; set; }
        public Nullable<byte> szin { get; set; }
    
        public virtual agencias agencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asociados> asociados { get; set; }
        public virtual ciudades ciudades { get; set; }
        public virtual nits nits { get; set; }
    }
}
