//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class hahorrosAtermino
    {
        public int año { get; set; }
        public int mes { get; set; }
        public string codlinea { get; set; }
        public int agencia { get; set; }
        public string numerocuenta { get; set; }
        public long Cedulasociado { get; set; }
        public Nullable<long> beneficiario1 { get; set; }
        public string nombrebeneficiario1 { get; set; }
        public Nullable<long> beneficiario2 { get; set; }
        public string nombrebeneficiario2 { get; set; }
        public System.DateTime fechainicio { get; set; }
        public Nullable<System.DateTime> fechaRenovacion { get; set; }
        public Nullable<System.DateTime> fecharenovainteres { get; set; }
        public Nullable<System.DateTime> f_ultimatransaccion { get; set; }
        public int PeriodoLiquida { get; set; }
        public int plazo { get; set; }
        public Nullable<decimal> tasacaptacion { get; set; }
        public string pignorado { get; set; }
        public string modalidad { get; set; }
        public Nullable<decimal> saldototal { get; set; }
        public Nullable<decimal> interesanticipado { get; set; }
        public Nullable<decimal> interescausado { get; set; }
        public string capitaliza { get; set; }
        public Nullable<decimal> interedisponible { get; set; }
        public string codlineaahorros { get; set; }
        public string nrocuentaahorros { get; set; }
        public Nullable<decimal> tasacaptacionanterior { get; set; }
        public Nullable<System.DateTime> f_ultimacausacion { get; set; }
        public Nullable<decimal> rtefteacumulada { get; set; }
        public Nullable<decimal> gmfmesasociado { get; set; }
        public Nullable<decimal> gmfmesentidad { get; set; }
        public Nullable<decimal> acumuladoretiros { get; set; }
        public Nullable<System.DateTime> fechavencimientocapital { get; set; }
        public Nullable<System.DateTime> fechavencimientointeres { get; set; }
        public string operador { get; set; }
        public System.DateTime fecharealcreacion { get; set; }
        public int agenciaoriginalmes { get; set; }
        public Nullable<decimal> valortitulo { get; set; }
        public Nullable<bool> web { get; set; }
        public decimal idhahorrosAtermino { get; set; }
        public Nullable<byte> szin { get; set; }
        public string origenfondos { get; set; }
        public Nullable<System.DateTime> f_sgtevctoktal { get; set; }
    }
}
