//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class hAportesSociales
    {
        public int año { get; set; }
        public int mes { get; set; }
        public string codlinea { get; set; }
        public string numerocuenta { get; set; }
        public long cedulasociado { get; set; }
        public Nullable<decimal> saldoTotal { get; set; }
        public System.DateTime fechaapertura { get; set; }
        public string formaPago { get; set; }
        public int agencia { get; set; }
        public Nullable<decimal> morosidad { get; set; }
        public Nullable<System.DateTime> f_ultimatransaccion { get; set; }
        public Nullable<decimal> Porcentajesalario { get; set; }
        public Nullable<decimal> Porcentajecuota { get; set; }
        public Nullable<decimal> valorcuota { get; set; }
        public string tipocuota { get; set; }
        public Nullable<decimal> acumuladoretiros { get; set; }
        public Nullable<decimal> multiplicador { get; set; }
        public Nullable<System.DateTime> fechainiciodeduccion { get; set; }
        public Nullable<bool> web { get; set; }
        public string estado { get; set; }
        public decimal idhAportesSociales { get; set; }
        public Nullable<byte> szin { get; set; }
    }
}
