//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcreditos
    {
        public int año { get; set; }
        public int mes { get; set; }
        public Nullable<long> cedulasociado { get; set; }
        public string codlinea { get; set; }
        public string coddestino { get; set; }
        public string codgarantia { get; set; }
        public Nullable<double> valorgarantia { get; set; }
        public decimal pagare { get; set; }
        public Nullable<System.DateTime> F_iniciofinanciacion { get; set; }
        public Nullable<System.DateTime> f_ultimacausacion { get; set; }
        public Nullable<System.DateTime> f_cargoprestamo { get; set; }
        public Nullable<System.DateTime> f_ultimopago { get; set; }
        public Nullable<decimal> capital { get; set; }
        public Nullable<decimal> capitalinicial { get; set; }
        public string cancelado { get; set; }
        public Nullable<decimal> tasacolocacion { get; set; }
        public string plazo { get; set; }
        public Nullable<decimal> anualidad { get; set; }
        public Nullable<decimal> intcorriente { get; set; }
        public Nullable<decimal> intmora { get; set; }
        public Nullable<decimal> intcorrientenocontabilizado { get; set; }
        public Nullable<decimal> intmoranocontabilizado { get; set; }
        public Nullable<decimal> saldocapital { get; set; }
        public string estado { get; set; }
        public string formapago { get; set; }
        public string adjetivo { get; set; }
        public string tipocuota { get; set; }
        public string modalidadinteres { get; set; }
        public string periodointeres { get; set; }
        public string modalidadcapital { get; set; }
        public string periodocapital { get; set; }
        public string asientonomina { get; set; }
        public string codoperador { get; set; }
        public Nullable<System.DateTime> fechasistema { get; set; }
        public Nullable<decimal> tasainicial { get; set; }
        public Nullable<decimal> tasaanterior { get; set; }
        public string libranza { get; set; }
        public string datacredito { get; set; }
        public Nullable<decimal> cuotainteres { get; set; }
        public string codsubdestino { get; set; }
        public string procredito { get; set; }
        public string juridico { get; set; }
        public Nullable<decimal> saldoponersedia { get; set; }
        public Nullable<decimal> cuotasmora { get; set; }
        public Nullable<int> diasmora { get; set; }
        public string prejuridico { get; set; }
        public string extrapordias { get; set; }
        public Nullable<decimal> tasanominal { get; set; }
        public Nullable<decimal> tasaefectiva { get; set; }
        public Nullable<System.DateTime> fechasaldoponersedia { get; set; }
        public Nullable<System.DateTime> fechavence { get; set; }
        public Nullable<bool> web { get; set; }
        public int diasmorareales { get; set; }
        public Nullable<byte> szin { get; set; }
    }
}
