//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lineas()
        {
            this.destinos = new HashSet<destinos>();
            this.tazasporplazos = new HashSet<tazasporplazos>();
        }
    
        public string codlinea { get; set; }
        public string codcuenta { get; set; }
        public string codcuentaingresocorrientes { get; set; }
        public string codcuentaingresosmora { get; set; }
        public short idlineas { get; set; }
        public Nullable<bool> zsisco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<destinos> destinos { get; set; }
        public virtual plancuentas plancuentas { get; set; }
        public virtual plancuentas plancuentas1 { get; set; }
        public virtual plancuentas plancuentas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tazasporplazos> tazasporplazos { get; set; }
    }
}
