//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class novedadesvariasnocausadas
    {
        public long cedulasociado { get; set; }
        public string codnovedad { get; set; }
        public Nullable<decimal> cuota { get; set; }
        public string formapago { get; set; }
        public Nullable<System.DateTime> fechacargo { get; set; }
        public Nullable<int> agencia { get; set; }
        public string estado { get; set; }
        public decimal idnovedadesvariasnocausadas { get; set; }
        public Nullable<System.DateTime> fechainiciodeduccion { get; set; }
        public Nullable<bool> web { get; set; }
        public string igualperiododeduce { get; set; }
        public Nullable<bool> zsisco { get; set; }
    
        public virtual agencias agencias { get; set; }
        public virtual asociados asociados { get; set; }
        public virtual cuentasnovedadesvarias cuentasnovedadesvarias { get; set; }
    }
}
