//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class parameahorroAlaVista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parameahorroAlaVista()
        {
            this.ahorrosalavista = new HashSet<ahorrosalavista>();
        }
    
        public string codlinea { get; set; }
        public decimal tasaCaptacion { get; set; }
        public string CodCuenta { get; set; }
        public int periodogracia { get; set; }
        public int periodoliquida { get; set; }
        public Nullable<int> periodoinactivo { get; set; }
        public Nullable<decimal> multiplicador { get; set; }
        public Nullable<decimal> saldominimoliquinteres { get; set; }
        public Nullable<decimal> saldominimocuenta { get; set; }
        public string codfuente { get; set; }
        public string cuentaretencion { get; set; }
        public string cuentagastointeres { get; set; }
        public string tipoliquidacion { get; set; }
        public string ManejaConsecutivo { get; set; }
        public string codcuentainactivos { get; set; }
        public string cuentacausa { get; set; }
        public string liquidaintereses { get; set; }
        public decimal cuotaminmensual { get; set; }
        public decimal cuotamaxmensual { get; set; }
        public string datoscomplementarios { get; set; }
        public string asignacuenta { get; set; }
        public string reconocerinteres { get; set; }
        public string controlaretiros { get; set; }
        public string permiteconclave { get; set; }
        public decimal valormax { get; set; }
        public short idparametro { get; set; }
        public string saldominimomaneja { get; set; }
        public Nullable<bool> web { get; set; }
        public Nullable<bool> zsisco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ahorrosalavista> ahorrosalavista { get; set; }
        public virtual plancuentas plancuentas { get; set; }
        public virtual plancuentas plancuentas1 { get; set; }
        public virtual plancuentas plancuentas2 { get; set; }
    }
}
