//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class sahorrospermanentes
    {
        public long nroregistro { get; set; }
        public string codlinea { get; set; }
        public string nrocuenta { get; set; }
        public System.DateTime fechatrabajo { get; set; }
        public string operador { get; set; }
        public Nullable<decimal> valorefectivo { get; set; }
        public Nullable<decimal> valorcheque { get; set; }
        public string documento { get; set; }
        public string natura { get; set; }
        public Nullable<System.DateTime> fechasistema { get; set; }
        public string numerodocumento { get; set; }
        public int agencia { get; set; }
        public Nullable<decimal> concepto { get; set; }
        public Nullable<decimal> tasa { get; set; }
        public Nullable<decimal> pagare { get; set; }
        public string estadotarjeta { get; set; }
        public int agenciatransaccion { get; set; }
        public Nullable<decimal> transito { get; set; }
        public string detalle { get; set; }
        public string recibo { get; set; }
        public decimal conceptotraslado { get; set; }
        public Nullable<decimal> saldoanterior { get; set; }
        public string consolidado { get; set; }
    
        public virtual agencias agencias { get; set; }
        public virtual ahorrospermanentes ahorrospermanentes { get; set; }
    }
}
