//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguimientocredito
    {
        public long registro { get; set; }
        public Nullable<long> cedulasociado { get; set; }
        public Nullable<System.DateTime> fechaTrabajo { get; set; }
        public string codoperador { get; set; }
        public Nullable<decimal> totalefectivo { get; set; }
        public string documento { get; set; }
        public string natura { get; set; }
        public decimal pagare { get; set; }
        public Nullable<System.DateTime> fechasistema { get; set; }
        public Nullable<decimal> tasacolocacion { get; set; }
        public Nullable<decimal> cuotainteres { get; set; }
        public Nullable<int> agencia { get; set; }
        public string tipocargo { get; set; }
        public string recibopago { get; set; }
        public int agenciatransaccion { get; set; }
        public string estadotarjeta { get; set; }
        public string codcuenta { get; set; }
        public decimal concepto { get; set; }
        public Nullable<int> pertenecepago { get; set; }
    
        public virtual agencias agencias { get; set; }
        public virtual agencias agencias1 { get; set; }
        public virtual creditos creditos { get; set; }
    }
}
