//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasasplazoahorrotermino
    {
        public int nroregistro { get; set; }
        public string codlinea { get; set; }
        public Nullable<int> plazo { get; set; }
        public Nullable<decimal> tasa { get; set; }
        public string moditasarenovacioninteres { get; set; }
        public string moditasarenoacioncapital { get; set; }
        public Nullable<int> PeriodoLiquida { get; set; }
        public string permitemodificar { get; set; }
        public Nullable<bool> web { get; set; }
    }
}
