//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasaspormontosyplazos
    {
        public short idparametrosahorroatermino { get; set; }
        public decimal montodesde { get; set; }
        public decimal montohasta { get; set; }
        public int plazodesde { get; set; }
        public int plazohasta { get; set; }
        public decimal tasa { get; set; }
        public string modificatasaen { get; set; }
        public decimal id { get; set; }
        public Nullable<int> periodoliquidadesde { get; set; }
        public Nullable<int> periodoliquidahasta { get; set; }
    }
}
