//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO.Ingenio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asociados_Ingenio
    {
        public int Id { get; set; }
        public string Identificacion { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoAPellido { get; set; }
        public string Correo { get; set; }
        public string Password { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaAnteriroAcceso { get; set; }
        public bool Activo { get; set; }
        public int tipo { get; set; }
    }
}
