//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingenio.BO.Ingenio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Imagen { get; set; }
        public string Html { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public bool NoticiaCofiFunda { get; set; }
        public string Url { get; set; }
        public int Id_Usuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
